### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by xeruf** [hashhar/dash-contrib-docset-feeds#2]
Stumbled upon this from https://github.com/zealdocs/zeal/issues/170 - how can I integrate this repo into Zeal? Maybe you could add that to the README as well ;)

**Comment by hashhar** [comment]
Sorry for the delayed response.

The process is to go to whatever file you want to add as a docset and then click the "Raw" button to get a URL of the file and then paste into Zeal's "Add Docset from feed URL".

I don't have a Linux machine handy at the moment so don't can't verify but this was the process if I remember correctly.

Another way you can add feeds in bulk is to clone this repository, run the `update.sh` script. It will create a file /tmp/docsets_url` with a URL per line. Keep the URLs you want to install docsets from and then run the commented section of the script at https://github.com/hashhar/dash-contrib-docset-feeds/blob/master/update.sh#L54-L62.

I'll try setting up a VM to verify and add the process but can't commit on when.

**Comment by hashhar** [comment]
Thanks to @soxofaan for submitting https://github.com/hashhar/dash-contrib-docset-feeds/pull/4 which is now merged and resolves this issue.
