### ISSUE TITLE
add missing docsets

### ISSUE THREAD

**Issue by pedrohgmacedo** [hashhar/dash-contrib-docset-feeds#6]
The following docsets exist in the dash user contrib repo, but are missing: polars, conda, bokeh, airflow, vega, visual studio code, altair, attrs, virtualenv, xarray.

I'd like to request to have them added.

**Comment by hashhar** [comment]
Thanks for bringing this to notice. Looks like my auto-update script needs adjustments.

I've figured out what the issue is and hope to have a fix in place by the end of this week so that on the coming Monday the auto-update adds the missing docsets too.
